// Token data generated by @uoa/tokens (dist/docs/tokens.json).
import data from '@uoa/tokens/docs.json';

export interface Token {
  name: string;
  path: string[];
  type: string;
  value: string | number;
  ref?: string;
  description?: string;
  tier: 'primitive' | 'semantic' | 'component' | 'themes';
}

export interface Theme {
  kind: 'brand' | 'accent';
  name: string;
  attribute: string;
  tokens: Token[];
}

export const tokens = data.tokens as Token[];
export const themes = data.themes as Theme[];

/** Tokens whose name starts with `--uoa-<prefix>`. */
export const byPrefix = (prefix: string, tier?: Token['tier']) =>
  tokens.filter((t) => t.name.startsWith(`--uoa-${prefix}`) && (!tier || t.tier === tier));

/** Resolved value of a token by CSS name. */
export const valueOf = (name: string) => tokens.find((t) => t.name === name)?.value;

function luminance(hex: string) {
  const [r, g, b] = [1, 3, 5].map((i) => {
    const c = parseInt(hex.slice(i, i + 2), 16) / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

export const contrastOnWhite = (hex: string) => 1.05 / (luminance(hex) + 0.05);
export const isDark = (hex: string) => luminance(hex) < 0.4;

export function contrastLevel(hex: string): { level: 'aa' | 'ui' | 'deco'; label: string; ratio: number } {
  const ratio = contrastOnWhite(hex);
  if (ratio >= 4.5) return { level: 'aa', label: 'AA', ratio };
  if (ratio >= 3) return { level: 'ui', label: 'UI', ratio };
  return { level: 'deco', label: 'Decorative', ratio };
}
